// Code generated by make contracts; DO NOT EDIT.

export interface ApiResponse<T = unknown> {
  success: boolean
  message?: string
  data?: T
  error?: string
  details?: string
}

export type ApiEnvelope<T = unknown> = ApiResponse<T>

export interface Decision {
  id: number
  alert_id: number
  origin: string
  source?: string
  type: string
  scope: string
  value: string
  duration: string
  scenario: string
  reason?: string
  created_at: string
  until?: string
}

export interface AddDecisionRequest {
  ip?: string
  range?: string
  duration?: string
  type?: string
  scope?: string
  value?: string
  reason?: string
  origin?: string
}

export interface DeleteDecisionRequest {
  id?: string
  ip?: string
  range?: string
  type?: string
  scope?: string
  value?: string
  scenario?: string
  origin?: string
}

export interface DecisionsResponse {
  decisions: Decision[]
  count: number
  total?: number
  limit?: number
  offset?: number
}

export interface BulkDeleteDecisionsRequest {
  ids: number[]
}

export interface BulkDeleteFailure {
  id: number
  error: string
}

export interface BulkDeleteDecisionsResponse {
  success_count: number
  failure_count: number
  deleted: number[]
  failed: BulkDeleteFailure[]
}

export interface AlertSource {
  cn?: string
  as_name?: string
  as_number?: string
  ip?: string
  range?: string
  latitude?: number
  longitude?: number
  scope?: string
  value?: string
}

export interface AlertEvent {
  timestamp: string
  meta?: Record<string, string>[]
}

export interface CrowdSecAlert {
  id: number
  scenario: string
  scope: string
  value: string
  origin: string
  type?: string
  message?: string
  events_count?: number
  start_at: string
  stop_at?: string
  capacity?: number
  leakspeed?: string
  simulated?: boolean
  decisions?: Decision[]
  source?: AlertSource | null
  events?: AlertEvent[]
}

export interface AlertsResponse {
  alerts: CrowdSecAlert[]
  count: number
}

export interface DecisionFilters {
  since?: string
  until?: string
  type?: string
  scope?: string
  origin?: string
  value?: string
  scenario?: string
  ip?: string
  range?: string
  includeAll?: boolean
  limit?: number
  offset?: number
}

export interface AlertFilters {
  since?: string
  until?: string
  ip?: string
  range?: string
  scope?: string
  value?: string
  scenario?: string
  type?: string
  origin?: string
  includeAll?: boolean
  limit?: number
  offset?: number
}

export interface DecisionHistoryRecord {
  id: number
  dedupe_key: string
  decision_id: number
  alert_id: number
  origin: string
  type: string
  scope: string
  value: string
  duration: string
  scenario: string
  created_at: string
  until?: string
  is_stale: boolean
  first_seen_at: string
  last_seen_at: string
  stale_at?: string
  last_snapshot_at: string
}

export interface DecisionHistoryResponse {
  decisions: DecisionHistoryRecord[]
  count: number
  total: number
}

export interface AlertHistoryRecord {
  id: number
  dedupe_key: string
  alert_id: number
  scenario: string
  scope: string
  value: string
  origin: string
  type?: string
  events_count: number
  start_at?: string
  stop_at?: string
  is_stale: boolean
  first_seen_at: string
  last_seen_at: string
  stale_at?: string
  last_snapshot_at: string
}

export interface AlertHistoryResponse {
  alerts: AlertHistoryRecord[]
  count: number
  total: number
}

export interface RepeatedOffender {
  value: string
  scope: string
  hit_count: number
  window_days: number
  first_decision_at: string
  last_decision_at: string
  last_notified_at?: string
}

export interface ReapplyDecisionRequest {
  id: number
  type: string
  duration: string
  reason?: string
}

export interface BulkReapplyDecisionsRequest {
  ids: number[]
  type: string
  duration: string
  reason?: string
}

export interface BulkReapplyResult {
  succeeded: number
  failed: number
  already_active?: number
  decision_ids?: number[]
  errors?: string[]
}

export interface HistoryStats {
  total_decisions: number
  active_decisions: number
  total_alerts: number
  active_alerts: number
  repeated_offender_count: number
}

export interface HistoryActivityBucket {
  ts: string
  alerts: number
  decisions: number
}

export interface HistoryActivityResponse {
  window: string
  bucket: string
  buckets: HistoryActivityBucket[]
  generated_at: string
  latest_snapshot_at: string | null
}

