/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitelistRouteImport } from './routes/whitelist'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as IpManagementRouteImport } from './routes/ip-management'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as CaptchaRouteImport } from './routes/captcha'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as AllowlistRouteImport } from './routes/allowlist'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const WhitelistRoute = WhitelistRouteImport.update({
  id: '/whitelist',
  path: '/whitelist',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IpManagementRoute = IpManagementRouteImport.update({
  id: '/ip-management',
  path: '/ip-management',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptchaRoute = CaptchaRouteImport.update({
  id: '/captcha',
  path: '/captcha',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AllowlistRoute = AllowlistRouteImport.update({
  id: '/allowlist',
  path: '/allowlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/allowlist': typeof AllowlistRoute
  '/backups': typeof BackupsRoute
  '/captcha': typeof CaptchaRoute
  '/configuration': typeof ConfigurationRoute
  '/decisions': typeof DecisionsRoute
  '/health': typeof HealthRoute
  '/ip-management': typeof IpManagementRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/profiles': typeof ProfilesRoute
  '/scenarios': typeof ScenariosRoute
  '/services': typeof ServicesRoute
  '/whitelist': typeof WhitelistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/allowlist': typeof AllowlistRoute
  '/backups': typeof BackupsRoute
  '/captcha': typeof CaptchaRoute
  '/configuration': typeof ConfigurationRoute
  '/decisions': typeof DecisionsRoute
  '/health': typeof HealthRoute
  '/ip-management': typeof IpManagementRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/profiles': typeof ProfilesRoute
  '/scenarios': typeof ScenariosRoute
  '/services': typeof ServicesRoute
  '/whitelist': typeof WhitelistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/allowlist': typeof AllowlistRoute
  '/backups': typeof BackupsRoute
  '/captcha': typeof CaptchaRoute
  '/configuration': typeof ConfigurationRoute
  '/decisions': typeof DecisionsRoute
  '/health': typeof HealthRoute
  '/ip-management': typeof IpManagementRoute
  '/logs': typeof LogsRoute
  '/notifications': typeof NotificationsRoute
  '/profiles': typeof ProfilesRoute
  '/scenarios': typeof ScenariosRoute
  '/services': typeof ServicesRoute
  '/whitelist': typeof WhitelistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/allowlist'
    | '/backups'
    | '/captcha'
    | '/configuration'
    | '/decisions'
    | '/health'
    | '/ip-management'
    | '/logs'
    | '/notifications'
    | '/profiles'
    | '/scenarios'
    | '/services'
    | '/whitelist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/allowlist'
    | '/backups'
    | '/captcha'
    | '/configuration'
    | '/decisions'
    | '/health'
    | '/ip-management'
    | '/logs'
    | '/notifications'
    | '/profiles'
    | '/scenarios'
    | '/services'
    | '/whitelist'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/allowlist'
    | '/backups'
    | '/captcha'
    | '/configuration'
    | '/decisions'
    | '/health'
    | '/ip-management'
    | '/logs'
    | '/notifications'
    | '/profiles'
    | '/scenarios'
    | '/services'
    | '/whitelist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AllowlistRoute: typeof AllowlistRoute
  BackupsRoute: typeof BackupsRoute
  CaptchaRoute: typeof CaptchaRoute
  ConfigurationRoute: typeof ConfigurationRoute
  DecisionsRoute: typeof DecisionsRoute
  HealthRoute: typeof HealthRoute
  IpManagementRoute: typeof IpManagementRoute
  LogsRoute: typeof LogsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfilesRoute: typeof ProfilesRoute
  ScenariosRoute: typeof ScenariosRoute
  ServicesRoute: typeof ServicesRoute
  WhitelistRoute: typeof WhitelistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitelist': {
      id: '/whitelist'
      path: '/whitelist'
      fullPath: '/whitelist'
      preLoaderRoute: typeof WhitelistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-management': {
      id: '/ip-management'
      path: '/ip-management'
      fullPath: '/ip-management'
      preLoaderRoute: typeof IpManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captcha': {
      id: '/captcha'
      path: '/captcha'
      fullPath: '/captcha'
      preLoaderRoute: typeof CaptchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allowlist': {
      id: '/allowlist'
      path: '/allowlist'
      fullPath: '/allowlist'
      preLoaderRoute: typeof AllowlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AllowlistRoute: AllowlistRoute,
  BackupsRoute: BackupsRoute,
  CaptchaRoute: CaptchaRoute,
  ConfigurationRoute: ConfigurationRoute,
  DecisionsRoute: DecisionsRoute,
  HealthRoute: HealthRoute,
  IpManagementRoute: IpManagementRoute,
  LogsRoute: LogsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfilesRoute: ProfilesRoute,
  ScenariosRoute: ScenariosRoute,
  ServicesRoute: ServicesRoute,
  WhitelistRoute: WhitelistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
