{{- if and .Values.persistence.logs.enabled (not .Values.persistence.logs.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "crowdsec-manager.fullname" . }}-logs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crowdsec-manager.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
  {{- if .Values.persistence.logs.storageClass }}
  storageClassName: {{ .Values.persistence.logs.storageClass }}
  {{- end }}
{{- end }}
