package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"crowdsec-manager/pkg/contracts"
)

type contractType struct {
	name string
	typ  reflect.Type
}

var contractTypes = []contractType{
	{"Decision", reflect.TypeOf(contracts.Decision{})},
	{"AddDecisionRequest", reflect.TypeOf(contracts.AddDecisionRequest{})},
	{"DeleteDecisionRequest", reflect.TypeOf(contracts.DeleteDecisionRequest{})},
	{"DecisionsResponse", reflect.TypeOf(contracts.DecisionsResponse{})},
	{"BulkDeleteDecisionsRequest", reflect.TypeOf(contracts.BulkDeleteDecisionsRequest{})},
	{"BulkDeleteFailure", reflect.TypeOf(contracts.BulkDeleteFailure{})},
	{"BulkDeleteDecisionsResponse", reflect.TypeOf(contracts.BulkDeleteDecisionsResponse{})},
	{"AlertSource", reflect.TypeOf(contracts.AlertSource{})},
	{"AlertEvent", reflect.TypeOf(contracts.AlertEvent{})},
	{"CrowdSecAlert", reflect.TypeOf(contracts.CrowdSecAlert{})},
	{"AlertsResponse", reflect.TypeOf(contracts.AlertsResponse{})},
	{"DecisionFilters", reflect.TypeOf(contracts.DecisionFilters{})},
	{"AlertFilters", reflect.TypeOf(contracts.AlertFilters{})},
	{"DecisionHistoryRecord", reflect.TypeOf(contracts.DecisionHistoryRecord{})},
	{"DecisionHistoryResponse", reflect.TypeOf(contracts.DecisionHistoryResponse{})},
	{"HistoryChartPoint", reflect.TypeOf(contracts.HistoryChartPoint{})},
	{"HistoryBreakdownItem", reflect.TypeOf(contracts.HistoryBreakdownItem{})},
	{"DecisionHistoryAnalysisResponse", reflect.TypeOf(contracts.DecisionHistoryAnalysisResponse{})},
	{"AlertHistoryRecord", reflect.TypeOf(contracts.AlertHistoryRecord{})},
	{"AlertHistoryResponse", reflect.TypeOf(contracts.AlertHistoryResponse{})},
	{"RepeatedOffender", reflect.TypeOf(contracts.RepeatedOffender{})},
	{"ReapplyDecisionRequest", reflect.TypeOf(contracts.ReapplyDecisionRequest{})},
	{"BulkReapplyDecisionsRequest", reflect.TypeOf(contracts.BulkReapplyDecisionsRequest{})},
	{"BulkReapplyResult", reflect.TypeOf(contracts.BulkReapplyResult{})},
	{"HistoryStats", reflect.TypeOf(contracts.HistoryStats{})},
	{"HistoryActivityBucket", reflect.TypeOf(contracts.HistoryActivityBucket{})},
	{"HistoryActivityResponse", reflect.TypeOf(contracts.HistoryActivityResponse{})},
}

func main() {
	out, err := render()
	if err != nil {
		fmt.Fprintf(os.Stderr, "render contracts: %v\n", err)
		os.Exit(1)
	}

	for _, target := range []string{
		"web/src/lib/api/contracts.generated.ts",
		"mobile/src/lib/api/contracts.generated.ts",
	} {
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "create target dir %s: %v\n", target, err)
			os.Exit(1)
		}
		if err := os.WriteFile(target, out, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "write %s: %v\n", target, err)
			os.Exit(1)
		}
	}
}

func render() ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by make contracts; DO NOT EDIT.\n\n")
	buf.WriteString("export interface ApiResponse<T = unknown> {\n")
	buf.WriteString("  success: boolean\n")
	buf.WriteString("  message?: string\n")
	buf.WriteString("  data?: T\n")
	buf.WriteString("  error?: string\n")
	buf.WriteString("  details?: string\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export type ApiEnvelope<T = unknown> = ApiResponse<T>\n\n")

	for _, item := range contractTypes {
		if item.typ.Kind() != reflect.Struct {
			return nil, fmt.Errorf("%s is %s, expected struct", item.name, item.typ.Kind())
		}
		writeInterface(&buf, item.name, item.typ)
	}
	return buf.Bytes(), nil
}

func writeInterface(buf *bytes.Buffer, name string, typ reflect.Type) {
	fmt.Fprintf(buf, "export interface %s {\n", name)
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		jsonName, optional := jsonField(field)
		if jsonName == "" {
			continue
		}
		fmt.Fprintf(buf, "  %s%s: %s\n", jsonName, optionalMark(optional), tsType(field.Type))
	}
	buf.WriteString("}\n\n")
}

func jsonField(field reflect.StructField) (string, bool) {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", false
	}
	name := field.Name
	optional := false
	if tag != "" {
		parts := strings.Split(tag, ",")
		if parts[0] != "" {
			name = parts[0]
		}
		for _, part := range parts[1:] {
			if part == "omitempty" {
				optional = true
			}
		}
	}
	return name, optional
}

func optionalMark(optional bool) string {
	if optional {
		return "?"
	}
	return ""
}

func tsType(typ reflect.Type) string {
	for typ.Kind() == reflect.Pointer {
		return tsType(typ.Elem()) + " | null"
	}

	switch typ.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		return tsType(typ.Elem()) + "[]"
	case reflect.Map:
		return fmt.Sprintf("Record<%s, %s>", tsType(typ.Key()), tsType(typ.Elem()))
	case reflect.Interface:
		return "unknown"
	case reflect.Struct:
		return typ.Name()
	default:
		return "unknown"
	}
}
